# Generated by Django 2.0.6 on 2018-06-24 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meds', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='meds.Category')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to='meds.Profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spr', to='meds.SprService')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
