# Generated by Django 2.0.6 on 2018-06-24 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meds', '0005_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meds.Advice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
