# Generated by Django 2.0.6 on 2018-06-24 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meds.utils.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meds', '0006_pointtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('problem', models.TextField()),
                ('diagnoz', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advices', to='meds.Category')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advices', to='meds.Doctor')),
                ('patient', models.ForeignKey(default=meds.utils.current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
