# Generated by Django 2.0.6 on 2018-06-24 17:23

from django.db import migrations


def migrate_categories(apps, schema_editor):
    cat = apps.get_model('meds', 'Category')
    cat.objects.create(title='Педиатрия', description='Мы позаботимся о здоровье ваших детей')
    cat.objects.create(title='Терапия', description='А как давно вы проходили профосмотр? ПОзаботьтесь о себе!')
    cat.objects.create(title='Кардиология', description='Сердце - двигатель вашей жизни! Берегите его!')
    cat.objects.create(title='Хирургия', description='Лучшие хирурги ответят на ваши вопросы')
    cat.objects.create(title='Гинекология', description='Консультации женского здоровья и планирования семьи')
    cat.objects.create(title='Офтольмология', description='Посмотрите на мир другими глазами')


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0009_adviceresult'),
    ]

    operations = [
        migrations.RunPython(migrate_categories, migrations.RunPython.noop)
    ]
