# Generated by Django 2.0.6 on 2018-06-24 17:44

from django.db import migrations


def migrate_price_service(apps, schema_editor):
    service = apps.get_model('meds', 'SprService')
    service.objects.create(title='Педиатр 1 кат.', price=20)
    service.objects.create(title='Педиатр доцент', price=30)
    service.objects.create(title='Педиатр профессор', price=50)
    service.objects.create(title='Хирургия 1 кат.', price=15)
    service.objects.create(title='Хирургия доцент', price=35)
    service.objects.create(title='Терапевт', price=10)
    service.objects.create(title='Семейный врач', price=25)
    service.objects.create(title='Кардиолог', price=50)
    


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0010_auto_20180624_1723'),
    ]

    operations = [
        migrations.RunPython(migrate_price_service, migrations.RunPython.noop)
    ]
