# Generated by Django 2.0.6 on 2018-06-24 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meds.utils.current_user


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0011_auto_20180624_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=meds.utils.current_user.get_current_user, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
